name: aaai_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - tqdm
  - lightgbm
  - prophet           
  - pmdarima
  - pyarrow
  - fastparquet
  - mlflow
  - statsmodels
  - matplotlib
  - seaborn
  - plotly
  - pytest
  - black
  - isort
  - db-dtypes
  - pip
  - pip:
      - torch
      - codecarbon
